### ISSUE TITLE
Lua module with "vendored" feature on Windows

### ISSUE THREAD

**Issue by Smertig** [khvzak/mlua#173]
Hi.

I was looking for a Rust library that would allow me to write self-contained native lua modules. `mlua` looks like a great candidate for that, however I found that "vendored module" feature [doesn't work](https://github.com/khvzak/mlua/blob/d9ac7abff2d605f8345657b1625eb3e2de02ddd8/build/main.rs#L101-L106) on Windows. So I have two questions:
1. Does it mean that native lua modules on Windows would always have dependency on `luaXX.dll`?
2. What _exactly_ prevents `mlua` from supporting this feature? I could probably dig a bit deeper into this problem, but I don't know where to start.

Thanks in advance

**Comment by khvzak** [comment]
I'm not sure what is "self-contained native lua modules"? If you refer to modules that linked with Lua core, this is anti-pattern that leads to crashes and segfaults and hard to debug issues. Actually that happened before, see #4 , since then I disabled vendored module mode on Windows.

On linux/macos/etc this can be easily solved by linking with runtime symbols resolution. I'm not sure how to do this on Windows as don't work on this OS and have almost no experience with it. The [Building Modules](http://lua-users.org/wiki/BuildingModules) wiki page explicitly recommends to link modules with a Lua dll.

**Comment by Smertig** [comment]
Thanks you for a detailed explanation.

By self-contained modules I mean lua modules that are statically linked with lua core, yes. Now I see why it's a bad idea (there's a really good example in #4), so I'll try to dynamically link lua core.
