### ISSUE TITLE
Add Yuescript support

### ISSUE THREAD

**Issue by Tarik02** [khvzak/mlua#188]
https://yuescript.org/

**Comment by hack3ric** [comment]
Personal opinion: Languages that *compiles* to Lua should not be included in Lua bindings.

Similar to the fact that V8 (to be exact, rusty_v8) does not include a TypeScript compiler, the work should be done somewhere else, and mlua only runs the output Lua code.

Luau is a dialect of Lua that runs on its own runtime, not compiled to Lua, so that's fine.

**Comment by Tarik02** [comment]
> Personal opinion: Languages that _compiles_ to Lua should not be included in Lua bindings.
> 
> Similar to the fact that V8 (to be exact, rusty_v8) does not include a TypeScript compiler, the work should be done somewhere else, and mlua only runs the output Lua code.
> 
> Luau is a dialect of Lua that runs on its own runtime, not compiled to Lua, so that's fine.

The problem is that yuescript (optionally) supports metaprogramming feature called macro which requires Lua interpreter to operate. It actually uses Lua to import (resolve) and evaluate these macro.
If you turn off this feature (compile time setting) you turn off macro support at all.

**Comment by hack3ric** [comment]
> > Personal opinion: Languages that _compiles_ to Lua should not be included in Lua bindings.
> 
> > 
> 
> > Similar to the fact that V8 (to be exact, rusty_v8) does not include a TypeScript compiler, the work should be done somewhere else, and mlua only runs the output Lua code.
> 
> > 
> 
> > Luau is a dialect of Lua that runs on its own runtime, not compiled to Lua, so that's fine.
> 
> 
> 
> The problem is that yuescript (optionally) supports metaprogramming feature called macro which requires Lua interpreter to operate. It actually uses Lua to import (resolve) and evaluate these macro.
> 
> If you turn off this feature (compile time setting) you turn off macro support at all.

That all happens in compile time, not runtime, so compile it outside mlua and load the output Lua script is a good idea.

Adding transpiler will cause mlua to bloat in my opinion.

**Comment by Tarik02** [comment]
> > > Personal opinion: Languages that _compiles_ to Lua should not be included in Lua bindings.
> > 
> > 
> > > 
> > 
> > 
> > > Similar to the fact that V8 (to be exact, rusty_v8) does not include a TypeScript compiler, the work should be done somewhere else, and mlua only runs the output Lua code.
> > 
> > 
> > > 
> > 
> > 
> > > Luau is a dialect of Lua that runs on its own runtime, not compiled to Lua, so that's fine.
> > 
> > 
> > The problem is that yuescript (optionally) supports metaprogramming feature called macro which requires Lua interpreter to operate. It actually uses Lua to import (resolve) and evaluate these macro.
> > If you turn off this feature (compile time setting) you turn off macro support at all.
> 
> That all happens in compile time, not runtime, so compile it outside mlua and load the output Lua script is a good idea.
> 
> Adding transpiler will cause mlua to bloat in my opinion.

Actually, luau includes compiler and (almost) regular lua runtime, so you are wrong. Looking at mlua binding, you can see it has special Compiler abstraction for luau.

**Comment by hack3ric** [comment]
> > > > Personal opinion: Languages that _compiles_ to Lua should not be included in Lua bindings.
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > Similar to the fact that V8 (to be exact, rusty_v8) does not include a TypeScript compiler, the work should be done somewhere else, and mlua only runs the output Lua code.
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > Luau is a dialect of Lua that runs on its own runtime, not compiled to Lua, so that's fine.
> > > 
> > > 
> > > The problem is that yuescript (optionally) supports metaprogramming feature called macro which requires Lua interpreter to operate. It actually uses Lua to import (resolve) and evaluate these macro.
> > > If you turn off this feature (compile time setting) you turn off macro support at all.
> > 
> > 
> > That all happens in compile time, not runtime, so compile it outside mlua and load the output Lua script is a good idea.
> > Adding transpiler will cause mlua to bloat in my opinion.
> 
> Actually, luau includes compiler and (almost) regular lua runtime, so you are wrong. Looking at mlua binding, you can see it has special Compiler abstraction for luau.

PUC-Rio Lua also has a compiler, which compiles to bytecode, the same way Luau does. LuaJIT is basically a JIT compiler. Those Lua *implementations* does not rely on other implementations to run. It's like the relationship between CPython, PyPy and Jython, or V8, JavaScriptCore and SpiderMonkey.

Yue compiles to Lua, not bytecode, and it also uses vanilla Lua/LuaJIT/Luau to execute its code. That's why it's called *trans*piler. And you cannot integrate Yue without one of those Lua implementations. Yue to Lua is the same as TypeScript/CoffeeScript to JavaScript. There's no TypeScript bindings, only JavaScript ones.

Another point of view: Yes, Luau adds type notations, but it is ignored during runtime just like Python does. It doesn't change much of the language's shape. Most Lua 5.1 code will still run on Luau (and LuaJIT of course). And it brings about a lot of the security features. Yue and MoonScript, on the other hand, adds a ton of sugar on top of Lua and makes it a completely different language. A Lua script will not run on "Yue VM" (assuming that exists).

If you really, really need to run Yue on mlua, you could implement a preprocessor. Here shows a function, but you can also write a macro to do it at compile time.

```rust
fn yue(code: &[u8]) -> Vec<u8> {
  // compile the code into Lua
}

lua
  .load(yue(r#"
  func = ->
    value = 100
    print "The value:", value
  func!
  "#))
  .exec()?
```

**Comment by Tarik02** [comment]
@hack3ric

Actually, there's no big problem to use Yuescript compiler as separate dependency, but the whole problem is that is itself requires some Lua implementation to work.

Is there a way to get at least include dirs of Lua implementation and compiler definitions from mlua package during build stage of some other package?

**Comment by hack3ric** [comment]
> @hack3ric
> 
> 
> 
> Actually, there's no big problem to use Yuescript compiler as separate dependency, but the whole problem is that is itself requires some Lua implementation to work.
> 
> 
> 
> Is there a way to get at least include dirs of Lua implementation and compiler definitions from mlua package during build stage of some other package?

I see, that's a problem indeed. 
Maybe linking Lua the same way mlua does? 

You can also have a look at `lua-src-rs` crate, but I'm no C expert so that's all I know.

**Comment by Tarik02** [comment]
> > @hack3ric
> > Actually, there's no big problem to use Yuescript compiler as separate dependency, but the whole problem is that is itself requires some Lua implementation to work.
> > Is there a way to get at least include dirs of Lua implementation and compiler definitions from mlua package during build stage of some other package?
> 
> I see, that's a problem indeed. Maybe linking Lua the same way mlua does?
> 
> You can also have a look at `lua-src-rs` crate, but I'm no C expert so that's all I know.

The problem is that Lua does not have stable C api even between versions like 5.3 and 5.4. And I did not touch other implementations like Luau.

The whole problem is that you can't get know how did mlua include Lua and which version of Lua is included (actually, it can include vendored version with static linking or system version with dynamic linking). Theoretically include path and definitions are enought.

I can get them like mlua does, but it has not simple logic and requires to compile artifacts to get header files and does not give any information about compiler definitions that are used. And I have to repeat the same features list I use when I include mlua itself.

**Comment by hack3ric** [comment]
@Tarik02

That's the limitation of Cargo I think. If you don't like to repeat the same features, you can re-export the mlua crate in your own Yue implementation and link those mlua features one by one:

```toml
# Cargo.toml

[package]
name = "yue"
version = "0.1.0"

[features]
lua51 = ["mlua/lua51"]
lua52 = ["mlua/lua52"]
# ...and so on

[dependencies]
mlua = "0.8.1"
```

```rust
// src/lib.rs
pub use mlua::*;
```

My opinion is that Yue integration is not the things mlua should do. Since mlua is licensed MIT, you may be able to use its logic under `build` and put it on your crate to use Lua. I don't oppose that mlua provide (if possible) a way to export those Lua implementation and compiler definition though.

Also, transpiling the source code in advance is recommended. If that's the case, a separate tool is, without doubt, a better method.

**Comment by khvzak** [comment]
I agree with @hack3ric that mlua itself is not the best place to support transpilers or other languages built on top of Lua VM.

Moreover, tomorrow someone else might want to add _moonscript_, then _haxe_ and so on. What makes `yuescript` uniq?
Adding a new feature flag to support _a new Lua VM fork_ or _a new language_ is a major step that requires huge effort to maintain it. Regular updates, testing, checking compatibility, etc. And _yuescript_ does not look as a right candidate for me. What if tommorow the author abandon it? There is only a little community around it and I don't see strong use cases.

The good news is that mlua is designed to easily integrate a libraries such as yuescript!
In your app you can build their C/C++ code and than register `yue` handler using [`Lua:: load_from_function`](https://docs.rs/mlua/0.8.1/mlua/struct.Lua.html#method.load_from_function) in combination with [`Lua::create_c_function`](https://docs.rs/mlua/0.8.1/mlua/struct.Lua.html#method.create_c_function).

`mlua` does provide access to raw `*mut lua_State` pointer through a C callback [`lua_CFunction`](https://docs.rs/mlua/0.8.1/mlua/type.lua_CFunction.html).
Also `mlua` provides for app build script path to Lua includes and libraries too. They are available via environment variables `DEP_LUA_INCLUDE` and `DEP_LUA_LIB`.

See an example I created to show how to use mlua with yuescript: https://github.com/khvzak/yuescript-mlua

**Comment by Tarik02** [comment]
@khvzak thank you! That's the thing I needed, just didn't know where to look for it.
