### ISSUE TITLE
missing `()` ToLua implementation

### ISSUE THREAD

**Issue by makspll** [khvzak/mlua#193]
`()` only has a ToLuaMulti implementation which doesn't seem quite right, this is likely due to the way ToLuaMulti is derived,

I think `()` should implement ToLua to enable making use of zero-sized types through values generic over `ToLua`

**Comment by khvzak** [comment]
Logically it makes sense to implement `ToLuaMulti ` for `()` as it represents "nothing on the stack" state.
Whereas `ToLua` belongs to a single value on a stack, which is _always_ something, like`Value::Nil` (ie. must be present).

zero-sized type like `()` is allowed for functions only, as an argument or return value, where Lua allow to define a number of stack values to take and number of values to return. All other API methods require a real value.

Rust does not allow to implement `ToLua` for `()` since this conflicts with a generic `impl<T: ToLua> ToLuaMulti for T {}`.

**Comment by makspll** [comment]
Hmm, I suppose that makes sense, In fact I thought () translated to `Nil` which would explain my confusion! thanks!
