### ISSUE TITLE
Unable to run a LuaFunction with Userdata upvalues

### ISSUE THREAD

**Issue by barsoosayque** [khvzak/mlua#257]
I've been trying to implement event-driven `UserData`, but can't wrap my head around lua upvalues in mlua. Here is my lua script with a number of cases (the first case is what I'm trying to get to work):

```lua
require("world")

local goal = world.new_goal()
local player = world.get_player()

-- (1) This doesn't work: a destructed callback or destructed userdata method was called
local trigger1 = world.on_entity_move(player, function()
    if player:in_pos({-30, 0, -30}) then
        goal:complete()
    end
end)

-- (2) No upvalues, can run just fine
local trigger2 = world.on_entity_move(player, function()
    print("Hello world !")
end)

-- (3) If I bind trigger's function to player, it works. But to run the first case, I would also need to bind goal
local trigger3 = world.on_entity_move(player, function(target)
    if target:in_pos({-30, 0, -30}) then
        print("Goal complete !")
    end
end)

goal:add_triggers(trigger1, trigger2, trigger3)
```

Now, _goal_, _player_ and _trigger_ are all `UserData`, and on creation of each of them I cache it in the registry with `RegistryKey` (I also put trigger's function in the registry as well). However, after executing this script and then later calling `LuaFunction` stored in trigger I can't get the first case to work, it's just `CallbackDestructed` error. I would assume that I didn't event need to put my `UserData` into the registry, because it's an upvalue for triggers, and from what I understand, those are static-/global like values and therefore they are on the stack (? really not sure about this part).

Non-userdata upvalues seems to be working. I'm using:
`
mlua = { git = "https://github.com/khvzak/mlua.git", rev = "94f01e597c33d6d3c0a19d673c3d4b55b2553e9f", features = ["async", "send", "vendored", "luajit"] }
`

**Comment by khvzak** [comment]
`CallbackDestructed` error when accessing `UserData` can occur because of the following reasons:
1) Lua garbage collector destroyed it
2) UserData is destroyed via [`AnyUserData::take`](https://docs.rs/mlua/0.8.7/mlua/struct.AnyUserData.html#method.take) method
3) `UserData` is destoroyed because went out of [`Lua::scope`](https://docs.rs/mlua/0.8.7/mlua/struct.Lua.html#method.scope)

I can rule out the first case as UserData object stored in upvalue or registry would prevent it being GC collected.

Do you use `take()` method or trying to access userdata outside of scope?

**Comment by barsoosayque** [comment]
Ohh, I did use `take()` to implement `FromLua`. I didn't even think about it. Luckily my `UserData` is cheap to copy so I can `borrow::<U>()?.clone()`, and that fixes the issue (I don't even need to put them into the registry !). Many thanks !
