### ISSUE TITLE
Using rust-implemented userdata with Hash trait for consistent table access

### ISSUE THREAD

**Issue by filiptibell** [khvzak/mlua#324]
I am using mlua with Luau and have implemented a userdata in rust like so:

```rs
#[derive(Debug, Clone)]
pub struct MyStruct {
    global_unique_id: u128,
}

impl LuaUserData for MyStruct {
    // ...
}

impl Hash for MyStruct {
    fn hash<H: Hasher>(&self, state: &mut H) {
        self.global_unique_id.hash(state)
    }
}
```

and then in lua:

```lua
local ud = createMyStruct()
local ud2 = createMyStruct()

local tab = {}
tab[ud] = "Hello, world!"

print(tab[ud]) --> "Hello, world!"
print(tab[ud2]) --> nil
```

It seems like this works on a small scale, but at some point stops working (indexing with `ud` gives `nil`) and I'm not really sure why. Does implementing Hash make a difference at all here? If not, would it be possible to link lua table key hashing to rusts Hash trait?

**Comment by khvzak** [comment]
Indexing userdata always use pointer value as hash. It's impossible to change this behaviour. 
Regardless of scale and number of collisions, it should never return nil if value is stored in a map.

Bear in mind, having two instances of similar userdata (eg. `MyStruct{global_unique_id: 123}`) will always give two uniq pointers and cross indexing them would not work.

What you probably need is to make them singletone. Keep a table of already created instances and return an existing one instead of creating a new.

**Comment by filiptibell** [comment]
Thank you for the clarification, that makes sense to me why it's happening then. Keeping a map of all created structs by unique id is a bit more work but definitely doable and should solve it.
