### ISSUE TITLE
memory leak in lua module

### ISSUE THREAD

**Issue by rise0chen** [khvzak/mlua#348]
This is test code: https://github.com/rise0chen/test_mlua
Running results:
![image](https://github.com/khvzak/mlua/assets/12853908/813fc3b6-a04b-4919-8ea8-4cc4448e7119)

I think this bug is related to UserData of lua module

**Comment by rise0chen** [comment]
This bug only happed when build lua module with release.
No memory leak when  build lua module with debug.

**Comment by khvzak** [comment]
Why do you think there is a memory leak? Because of increased rss size?

**Comment by khvzak** [comment]
In lua5.3 the following code:
```
            lua.load("while true do sleep(1) end")
                .exec_async()
                .await
                .unwrap();
```
creates a new thread for each async execution, this is because Lua 5.3 cannot reuse thread for this (Lua 5.4 can).
Running it in a loop you create an excessive number of object for GC to collect.

If you update the Lua chunk code to `while true do sleep(1) collectgarbage() end` you will see that memory stays constant.
To keep memory footage lower you need to either tweak Lua GC to run it more frequently OR use to Lua 5.4 with [thread pool option](https://docs.rs/mlua/latest/mlua/struct.LuaOptions.html#structfield.thread_pool_size)
