### ISSUE TITLE
why i can require('ffi') , And i compile it with features 'luajit', luajit source code contain ffi model

### ISSUE THREAD

**Issue by rhettli** [khvzak/mlua#37]
```lua
local ffi = require("ffi")
ffi.cdef[[
void Sleep(int ms);
int poll(struct pollfd *fds, unsigned long nfds, int timeout);
]]
--  do something...
```
#### who can help me? thank you

see: http://luajit.org/extensions.html

---------------------
i check it again,not only ffi model have problem,

thread and debug hanve the same problem too.

you see...:

![屏幕截图 2021-03-10 213315](https://user-images.githubusercontent.com/26317003/110637531-73323c80-81e8-11eb-9d1f-9fb986fd3d64.png)

## left is jit c code right is lua code in rust, and below is error.

**Comment by khvzak** [comment]
`ffi` and `debug` modules are not available in safe mode because these libraries are marked as unsafe. In this mode even loading C modules is disabled (from the documentation).

Fortunately it's easy to fix, you could use `Lua::unsafe_new()` to load all standard modules.
```rust
use mlua::prelude::*;

fn main() -> LuaResult<()> {
    let lua = unsafe { Lua::unsafe_new() };

    lua.load(
        r#"
        local debug = require("debug")
        local ffi = require("ffi")
        ffi.cdef[[
            int printf(const char *fmt, ...);
        ]]

        ffi.C.printf("Hello %s!\n", "world")
    "#,
    )
    .exec()
}
```

Unfortunately I missed the `thread` module because it's not documented and not available in the LuaJIT 2.0.5.
Thanks for pointing this out, I'll probably include it to the next release requiring both `luajit` and `vendored` feature flags.
