### ISSUE TITLE
Luau support

### ISSUE THREAD

**Issue by Milo123459** [khvzak/mlua#59]
https://luau-lang.org/

**Comment by khvzak** [comment]
Luau does not support object finalizers (__gc metamethod) that makes it impossible to use with Rust.

**Comment by Milo123459** [comment]
Oh. Is there no work around?

**Comment by Milo123459** [comment]
Okay, is there no way to bypass this? Manually defining?

**Comment by khvzak** [comment]
By the way, I cannot find link to download Luau source code. Apparently it's a commercial product not publicly available.

**Comment by Milo123459** [comment]
I think there is a luau compiler?

**Comment by Milo123459** [comment]
Or - just use Lua 5.1 and add the type system.

**Comment by Milo123459** [comment]
https://github.com/Roblox/luau has now been opensourced.

**Comment by khvzak** [comment]
This is great news, I'll take a look, thanks!

**Comment by Milo123459** [comment]
Any updates? Hate to bump, but genuinely curious.

**Comment by khvzak** [comment]
No news yet. Luau is _very_ different from vanilla Lua and couple of weeks ago even didn't have C interface. 
Although I'm not sure about the current status of C interface.

**Comment by khvzak** [comment]
Just curious, any advantages to use Luau instead of normal Lua or luajit?

**Comment by Milo123459** [comment]
To be honest, I like using it for the types. It has TypeScript like types, which makes me more or less feel at home with it.

**Comment by ildar** [comment]
Typed Lua aka Teal might satisfy you with it.

**Comment by Milo123459** [comment]
There are also some other beta-features that I would like to use in Luau. Still, Teal does satisfy me (I use it a lot) this would be cool, still.

**Comment by grilme99** [comment]
Luau support would be great.

> Just curious, is there any advantages to use Luau instead of normal Lua or luajit?

This is covered in their [docs](https://luau-lang.org/why) but essentially the tl;dr is that it is progressively typed and the performance is on-par with LuaJIT in certain cases and outperforms standard Lua in all cases. Roblox could never use JIT themselves because certain target platforms either do not support it or do now allow it (e.g. Apple with iOS).

It's based on Lua 5.1 but sprinkles in some of the best parts of later Lua versions. Luau has an amazing sandbox built-in which can guarantee* safety, even when running completely arbitrary and actively malicious code - perfect for game mods etc. The sandbox also has support for interrupts, which is pretty nice.

**Comment by khvzak** [comment]
I pushed initial Luau support to the [dev branch](https://github.com/khvzak/mlua/tree/dev)
It passes tests and works in vendored only mode by default.

So the next mlua v0.8 will get luau support including emulating sime of the missed features like userdata values, `require`, etc.

**Comment by khvzak** [comment]
just released `v0.8.0-beta.1` with Luau support
