### ISSUE TITLE
UserData, FromLua and Clone

### ISSUE THREAD

**Issue by Lucky4Luuk** [khvzak/mlua#64]
Perhaps it's worth changing either the docs for UserData, or require UserData to be implemented only on structs implementing Clone? Otherwise, you can create a struct that implements UserData, but does not implement FromLua, which can lead to headscratching errors, as the docs state that UserData will provide you with an implementation of FromLua.

My usage, boiled down to its most basic form:
```rust
struct TestStruct {
    data: Arc<RandomData> //RandomData does not implement clone
}

impl UserData for TestStruct{} //Does not provide a FromLua implementation, because TestStruct does not implement Clone
```

**Comment by khvzak** [comment]
`UserData` does not require `Clone` because it can be used without this trait.
I agree about the documentation and will mention this requirement explicitly. Thanks for pointing this out.

`FromLua` for `UserData` can be useful if you want to get a non-borowed `UserData` instance. Otherwise you can use methods provided by `AnyUserData` to get a borrowed instance:
[`AnyUserData::borrow()`](https://docs.rs/mlua/0.6.2/mlua/struct.AnyUserData.html#method.borrow) and [`AnyUserData::borrow_mut()`](https://docs.rs/mlua/0.6.2/mlua/struct.AnyUserData.html#method.borrow_mut)
